---
deploy_key_owner: jenkins
deploys_key_group: jenkins
root_domain: "{{ enclave }}.{{ base_domain }}"
domain_delimiter: "-"
namespace: "{{ enclave }}"
source_secret_name: "{{ base_domain }}-tls"
airflow_db_schema: "{{ enclave }}"
airflow_db_enclave_user: "{{ enclave }}"