{{- if .Values.jenkins.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-jenkins-master-home"
  labels:
    app: "{{ .Release.Name }}-jenkins-master-home"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  accessModes:
    - {{ .Values.jenkins.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jenkins.persistence.size | quote }}
{{- if .Values.jenkins.persistence.storageClass }}
{{- if (eq "-" .Values.jenkins.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.jenkins.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}