---
- name: Configure kubectl using kops
  shell: "kops export kubecfg --name {{ cluster_name }} --state {{ state_store }}"
  
- name: Get initial helm status
  shell: helm list
  register: helm_list_initial_status
  ignore_errors: true

- name: Download helm
  get_url:
    url: "{{ helm_url }}" 
    dest: "{{ helm_temp_directory }}/helm.tar.gz"
  when: helm_list_initial_status.failed

- name: Make helm directory
  file:
    path: "{{ helm_temp_directory }}/helm"
    state: directory
  when: helm_list_initial_status.failed

- name: Unarchive helm
  unarchive:
    copy: no
    src: "{{ helm_temp_directory }}/helm.tar.gz"
    dest: "{{ helm_temp_directory }}/helm"
  when: helm_list_initial_status.failed

- name: Copy helm to bin
  become: yes
  with_items:
    - helm
  copy:
    remote_src: true
    src: "{{ helm_temp_directory }}/helm/linux-amd64/helm"
    dest: "{{ helm_bin_dest }}"
    mode: ugo=rx
  when: helm_list_initial_status.failed

- name: Cleanup helm
  with_items:
    - "helm"
    - "helm.tar.gz"
  file:
    path: "{{ helm_temp_directory }}/{{item}}"
    state: absent
  when: helm_list_initial_status.failed

- name: Check helm status
  shell: helm list
  register: helm_list_status
  ignore_errors: true
  when: helm_list_initial_status.failed

- name: Install helm's tiller and update helm repos
  shell: |
    kubectl create serviceaccount --namespace kube-system tiller
    sleep 1
    kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller
    sleep 1
    helm init --service-account tiller
    helm repo update
  when: helm_list_initial_status.failed and helm_list_status.stdout.find('could not find a ready tiller') == -1

- name: Wait for helm ready
  shell: helm ls
  register: helm_list_status_after_install
  until: helm_list_status_after_install.stdout.find('not find a ready tiller') == -1
  retries: 5
  delay: 10
  ignore_errors: true
  when: helm_list_initial_status.failed
