apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-redis"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-redis"
spec:
  selector:
    app: "{{ .Release.Name }}-redis"
  ports:
    - name: node
      protocol: TCP
      port: 6379
      targetPort: node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-redis"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-redis"
    app: "{{ .Release.Name }}-redis"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-redis"
      app: "{{ .Release.Name }}-redis"
  template:
    metadata:
      labels:
        component: "{{ .Release.Name }}-redis"
        app: "{{ .Release.Name }}-redis"
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: redis:3
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - name: node
          containerPort: 6379
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 3
        