{{- if .Values.nexus.enabled }}
{{- if .Values.nexus.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-nexus"
  labels:
    app: "{{ .Release.Name }}-nexus"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    {{- range $key, $value := .Values.nexus.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.nexus.docker.enabled }}
    - host: {{ .Values.nexus.docker.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ .Release.Name }}-nexus"
              servicePort: {{ .Values.nexus.docker.port }}
    {{- end }}
    - host: "{{ .Values.nexus.ingress.domain.partial }}.{{ .Values.rootDomain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ .Release.Name }}-nexus"
              servicePort: {{ .Values.nexus.port }}
    {{- if .Values.addLocalDomain }}
    - host: "{{ .Values.nexus.ingress.domain.partial }}.local.{{ .Values.rootDomain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: "{{ .Release.Name }}-nexus"
              servicePort: {{ .Values.nexus.port }}
    {{- end }}
  {{- if .Values.nexus.ingress.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.nexus.ingress.domain.partial }}.{{ .Values.rootDomain }}"
    {{- if .Values.nexus.ingress.tls.autoSecretNameDeduction }}
    secretName: "{{ .Values.rootDomain }}-tls"
    {{- else }}
    secretName: {{ .Values.nexus.ingress.tls.secretName  }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
