---

- name: Get Dex chart status
  shell: helm --kube-context {{ cluster_name }} status dex
  register: helm_dex_status
  ignore_errors: true
  when: dex.enabled
  tags: dex

- name: Create Dex configuration (values) file
  template:
    src: dex.yml.j2
    dest: "{{ tmp_dir }}/dex.{{ cluster_name }}.yml"
    mode: 0644
  when: dex.enabled and helm_dex_status.stdout.find("DEPLOYED") == -1
  tags: dex

- name: Install Dex
  command: "helm --kube-context {{ cluster_name }} install legion-helm/dex --name dex --version={{ legion_version }} --namespace kube-system -f {{ tmp_dir }}/dex.{{ cluster_name }}.yml --wait"
  when: dex.enabled and helm_dex_status.stdout.find("DEPLOYED") == -1
  tags: dex

- name: Get Ingress ELB endpoint
  shell: kubectl --context {{ cluster_name }} describe services dex --namespace kube-system |grep .elb.amazonaws.com| awk '{ print $3 }'
  register: dex_elb_endpoint
  until: dex_elb_endpoint.stdout.find(".elb.amazonaws.com") != -1
  retries: 10
  delay: 10
  when: dex.enabled
  tags: dex

- name: Create dex DNS record
  route53:
    state: present
    zone: "{{ route53_zone }}"
    record: "dex.{{ base_domain }}"
    ttl: 60
    type: CNAME
    value: "{{ dex_elb_endpoint.stdout }}"
    overwrite: true
  when: dex.enabled
  tags: dex