---

- name: Set list of logging buckets
  set_fact:
    list_logging_buckets:
      - "{{ kube_fluentd.kube_s3_bucket_name }}"
      - "{{ kube_fluentd.system_s3_bucket_name }}"
      - "{{ kube_fluentd.services_s3_bucket_name }}"

- name: Set unique list of logging buckets
  set_fact:
    logging_buckets: "{{ list_logging_buckets | unique }}"

- name: Create Kube Logging S3 bucket
  s3_bucket:
    name: "{{ kube_fluentd.kube_s3_bucket_name }}"
    region: "{{ kube_fluentd.kube_s3_bucket_region }}"
    state: present

- name: Create Systemd Logging S3 bucket
  s3_bucket:
    name: "{{ kube_fluentd.system_s3_bucket_name }}"
    region: "{{ kube_fluentd.system_s3_bucket_region }}"
    state: present

- name: Create Systemd Logging S3 bucket
  s3_bucket:
    name: "{{ kube_fluentd.system_s3_bucket_name }}"
    region: "{{ kube_fluentd.system_s3_bucket_region }}"
    state: present

- name: Create Services Logging S3 bucket
  s3_bucket:
    name: "{{ kube_fluentd.services_s3_bucket_name }}"
    region: "{{ kube_fluentd.services_s3_bucket_region }}"
    state: present

- name: Generate trust policy document
  template:
    src: "trust_policy.yaml.j2"
    dest: "{{ tmp_dir }}/trust_policy.kube-fluentd.{{ cluster_name }}.yaml"

- name: Generate fluentd s3 access policy document
  template:
    src: "fluentd_s3_access_policy.yaml.j2"
    dest: "{{ tmp_dir }}/fluentd_s3_access_policy.{{ cluster_name }}.yaml"

- name: Create fluentd S3 access role
  iam:
    iam_type: role
    name: "{{ cluster_name }}-fluentd-role"
    trust_policy_filepath: "{{ tmp_dir }}/trust_policy.kube-fluentd.{{ cluster_name }}.yaml"
    state: present
  retries: 10
  delay: 5

- name: Attach S3 accesse policy to the role
  iam_policy:
    iam_type: role
    iam_name: "{{ cluster_name }}-fluentd-role"
    policy_name: "{{ cluster_name }}-fluentd-s3-access-policy"
    policy_document: "{{ tmp_dir }}/fluentd_s3_access_policy.{{ cluster_name }}.yaml"
    state: present
  retries: 10
  delay: 5

- name: Create fluentd configuration (values) file
  template:
    src: fluentd-values.yaml.j2
    dest: "{{ tmp_dir }}/fluentd-values.{{ cluster_name }}.yaml"
    mode: 0644

- name: Delete kube-fluentd chart
  shell: helm --kube-context {{ cluster_name }} del --purge kube-fluentd
  ignore_errors: true

# Install charts from remote repo
- name: Install kube-fluentd chart
  shell: helm --kube-context {{ cluster_name }} install legion-helm/kube-fluentd --name kube-fluentd --version={{ legion_version }} --namespace=kube-system --wait --timeout 600 -f  {{ tmp_dir }}/fluentd-values.{{ cluster_name }}.yaml
  when: helm_local_src != 'true'
# OR install charts from local soures in case of debug flag
- name: Install kube-fluentd chart
  shell: helm --kube-context {{ cluster_name }} install kube-fluentd --name kube-fluentd --namespace=kube-system --wait --timeout 600 -f  {{ tmp_dir }}/fluentd-values.{{ cluster_name }}.yaml
  args:
    chdir: ../helms
  when: helm_local_src == 'true'