{{ if .Values.edge.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: edge
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments", "replicasets", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/rollback", "deployments/scale", "replicasets", "statefulsets", "services", "ingresses"]
  verbs:  ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/rollback", "deployments/scale", "replicasets", "statefulsets", "services", "ingresses"]
  verbs:  ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: edge
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: edge
roleRef:
  kind: Role
  name: edge
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge
{{- end }}
