---
- name: Add helm repositories
  shell: helm --kube-context {{ cluster_name }} repo add {{ item }}
  with_items:
    - jupyterhub https://jupyterhub.github.io/helm-chart/
    - default http://storage.googleapis.com/kubernetes-charts/

- name: Update helm repositories
  shell: helm --kube-context {{ cluster_name }} repo update

- name: Chmod HELM tools
  file:
    path: payloads/{{ item }}
    mode: a+rx
  with_items:
    - examine_helm_deployed
    - helm_delete_by_chart_name

- name: Download jq
  get_url:
    url: "{{ jq_download_url }}"
    dest: "/usr/bin/jq"
    owner: root
    group: root
    mode: a+rx
  become: yes
