{{ if .Values.edi.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-cluster-state"
data:
  cluster.yaml: |
    tenant: "{{ .Values.tenantName }}"
    namespace: "{{ .Release.Namespace }}"
    deployment: "{{ .Release.Name }}"
    domain: "{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
    consul:
      public: "consul{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
      domain: "{{ .Release.Name }}-consul.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 8500
    graphite: 
      domain: "{{ .Release.Name }}-graphite.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 8125
    grafana:
      public: "{{ .Values.grafana.ingress.domain.partial }}{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
      domain: "{{ .Release.Name }}-grafana.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 80
    edge:
      public: "{{ .Values.edge.ingress.domain.partial }}{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
      domain: "{{ .Release.Name }}-edge.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 80
    jupyter:
      public: "{{ .Values.jupyterhub.nfs.ingress.domain.partial }}{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
    ldap:
      public: "{{ .Values.ldap.gui.ingress.domain.partial }}{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-cluster-secrets"
type: Opaque
data:
  grafana.user: YWRtaW4=
  grafana.password: YWRtaW4=
{{- end }}

