{{ if .Values.edi.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}-cluster-state"
data:
  cluster.yaml: |
    enclave: "{{ .Values.enclaveName }}"
    namespace: "{{ .Release.Namespace }}"
    deployment: "{{ .Release.Name }}"
    domain: "{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
    graphite: 
      domain: "{{ .Release.Name }}-graphite.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 8125
    grafana:
      public: "{{ .Values.grafana.ingress.domain.partial }}{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
      domain: "{{ .Release.Name }}-grafana.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 80
    edge:
      public: "{{ .Values.edge.ingress.domain.partial }}{{ .Values.domainDelimiter }}{{ .Values.rootDomain }}"
      domain: "{{ .Release.Name }}-edge.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
      port: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-cluster-secrets"
type: Opaque
data:
  grafana.user: YWRtaW4=
  grafana.password: YWRtaW4=
# TODO: hardcoded values should be removed in future when closing LEGION #499
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-jwt-config"
type: Opaque
data:
  jwt.secret: "{{ .Values.secrets.token_secret | b64enc }}"
  jwt.length.minutes: "{{ .Values.secrets.token_ttl_minutes | b64enc }}"
  jwt.exp.datetime: "{{ .Values.secrets.token_exp_datetime | b64enc }}"
{{- end }}

