{{- if .Values.ldap.gui.enabled }}
apiVersion: v1
kind: ReplicationController
metadata:
  name: "{{ .Release.Name }}-ldap-gui"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-ldap-gui"
spec:
  replicas: {{ .Values.ldap.gui.replicas }}
  selector:
    component: "{{ .Release.Name }}-ldap-gui"
  template:
    metadata:
      labels:
        component: "{{ .Release.Name }}-ldap-gui"
    spec:
      containers:
      - name: phpldapadmin
        image: "{{ .Values.ldap.gui.image.repository }}:{{ .Values.ldap.gui.image.tag }}"
        imagePullPolicy: "{{ .Values.ldap.gui.image.pullPolicy }}"
        env:
        - name: PHPLDAPADMIN_LDAP_HOSTS
        {{- if .Values.ldap.gui.endpoint }}
          value: "{{ .Values.ldap.gui.endpoint }}"
        {{- else }}
          value: "{{ .Release.Name }}-ldap-server.{{ .Release.Namespace }}.svc.{{ .Values.localDomain }}"
        {{- end}}
        - name: PHPLDAPADMIN_HTTPS
          value: "false"
        - name: PHPLDAPADMIN_SERVER_PATH
          value: "/"
        ports:
        - containerPort: {{ .Values.ldap.gui.port }}
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-ldap-gui"
  labels:
    component: "{{ .Release.Name }}-ldap-gui"
spec:
  selector:
    component: "{{ .Release.Name }}-ldap-gui"
  ports:
  - name: http
    port: {{ .Values.ldap.gui.port }}
    protocol: TCP
---
{{- if .Values.ldap.gui.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ldap.gui.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-ldap-gui"
  name: "{{ .Release.Name }}-ldap-gui"
spec:
  rules:
    - host: "{{ .Values.ldap.gui.ingress.domain.partial }}.{{ .Values.rootDomain }}"
      http:
        paths:
          - backend:
              serviceName: "{{ .Release.Name }}-ldap-gui"
              servicePort: {{ .Values.ldap.gui.port }}
  {{- if .Values.ldap.gui.ingress.tls.enabled }}
  tls:
  - hosts:
    - "{{ .Values.ldap.gui.ingress.domain.partial }}.{{ .Values.rootDomain }}"
    {{- if .Values.ldap.gui.ingress.tls.autoSecretNameDeduction }}
    secretName: "{{ .Values.rootDomain }}-tls"
    {{- else }}
    secretName: {{ .Values.ldap.gui.ingress.tls.secretName  }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}