# Common
vendor: legion
env_type: test
env_name: legion-test
base_domain: legion-test.epm.kharlamov.biz
route53_zone: epm.kharlamov.biz

# AWS 
aws_region: us-east-2
node_autoscaler_min: 3
node_autoscaler_max: 5
bastion_shape: t2.micro
master_shape: t2.large
node_shape: t2.large
vpc_id: vpc-5729c13e
airflow_rds_shape: "db.t2.medium"
airflow_rds_size: "50"

# Kops
cluster_name: legion-test.epm.kharlamov.biz
state_store: s3://legion-cluster
aws_image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
kubernetes_version: 1.8.7
private_network: '172.31'
cluster_zones:
  - zone_name: us-east-2a
    kops_cidr: "{{ private_network }}.112.0/24"
    kops_utility_cidr: "{{ private_network }}.113.0/24"
  - zone_name: us-east-2b
    kops_cidr: "{{ private_network }}.114.0/24"
    kops_utility_cidr: "{{ private_network }}.115.0/24"
  - zone_name: us-east-2c
    kops_cidr: "{{ private_network }}.116.0/24"
    kops_utility_cidr: "{{ private_network }}.117.0/24"

# Legion specific variables
ssh_public_key: ~/.ssh/id_rsa.pub
certificate_email: Kirill_Makhonin@epam.com
git_key: "/home/jenkins/deploy.cert"
cert_dir: "/etc/dynssl"
use_https: "yes"
use_https_for_tests: "yes"
nexus_pypi_repo: "https://nexus-local.cc.epm.kharlamov.biz/repository/pypi-hosted/simple"
nexus_docker_repo: "nexus-local.cc.epm.kharlamov.biz:443"
namespace: default
deployment: legion
service_account:
  login:  admin
  password: admin
examples_to_test:
  - Test-Summation
  - Sklearn-Income
  - Digit-Recognition
enclaves:
  - company-a
storageclass: efs
airflow_s3_log_url: 's3://epm-legion-data-test/airflow-logs/'
airflow_s3_url: 's3://epm-legion-data-test/'
airflow_expected_output: 'expected-data/'
airflow_pvc: 200m
