# Common
vendor: legion
env_name: legion-ci-app
base_domain: legion-ci-app.epm.kharlamov.biz
route53_zone: epm.kharlamov.biz

# Logging
log_level: debug

# System vars
tmp_dir: /tmp/

# AWS
aws_region: us-east-2
node_autoscaler_min: 4
node_autoscaler_max: 5
bastion_shape: t2.micro
master_shape: m4.xlarge
node_shape: m4.xlarge

# Ohio high memory instances
node_extra_shapes:
  - r4.large    # 2 cpu   / 15.25Gb / $0.133 ph
  - r4.xlarge   # 4 cpu   / 30.5Gb  / $0.266 ph
  - r4.2xlarge  # 8 cpu   / 61Gb    / $0.532 ph
  - r4.4xlarge  # 16 cpu  / 122Gb   / $1.064 ph
  - r4.8xlarge  # 32 cpu  / 244Gb   / $2.128 ph
  - r4.16xlarge # 64 cpu  / 488Gb   / $4.256 ph
  - x1.16xlarge # 64 cpu  / 976Gb   / $6.669 ph
  - x1.32xlarge # 128 cpu / 1952Gb  / $13.338 ph

node_extra_min: 0
node_extra_max: 2

vpc_id: vpc-5729c13e

# Kops
cluster_name: legion-ci-app.epm.kharlamov.biz
state_store: s3://legion-cluster
cluster_ssh_public_key_path: "{{ tmp_dir }}/legion_id_rsa.pub"

private_network: '172.31'
cluster_zones:
  - zone_name: us-east-2a
    kops_cidr: "{{ private_network }}.130.0/24"
    kops_utility_cidr: "{{ private_network }}.131.0/24"
  - zone_name: us-east-2b
    kops_cidr: "{{ private_network }}.132.0/24"
    kops_utility_cidr: "{{ private_network }}.133.0/24"
  - zone_name: us-east-2c
    kops_cidr: "{{ private_network }}.134.0/24"
    kops_utility_cidr: "{{ private_network }}.135.0/24"
k8s_master_zones:
  - us-east-2a
default_cluster_roles: 
  - bastion.{{ cluster_name }}
  - masters.{{ cluster_name }}
  - nodes.{{ cluster_name }}

# Legion specific variables
persistent_jenkins_volume: true
ssh_public_key: ~/.ssh/id_rsa.pub
certificate_email: legion@epam.com
cert_dir: "/etc/dynssl"
use_https: "yes"
use_https_for_tests: "yes"
pypi_repo: "https://nexus-local.cc.epm.kharlamov.biz/repository/pypi-hosted/simple"
docker_repo: "nexus-local.cc.epm.kharlamov.biz:443/legion"
namespace: default
deployment: legion
examples_to_test:
  - Test-Summation
  - Digit-Recognition
model_id_to_test: income
enclaves:
  - company-a
storageclass: efs
legion_data_bucket_prefix: legion-data
legion_data_s3_bucket: "{{ legion_data_bucket_prefix }}-{{ env_name }}-{{ enclave }}"
max_token_ttl_minutes: 259200  # 60*24*180, 180 days

collector:
  replicas: 1
  region: "{{ aws_region }}"

# Addons
dashboard:
  version: "1.10.1"
  insecure: true

# Cluster logs
kube_fluentd:
  kube_s3_bucket_name: epm-legion-data-ci-app-logs
  kube_s3_bucket_region: us-east-2
  # kube_s3_bucket_prefix: cluster_logs
  system_s3_bucket_name: epm-legion-data-ci-app-logs
  system_s3_bucket_region: us-east-2
  # system_s3_bucket_prefix: cluster_logs
  services_s3_bucket_name: epm-legion-data-ci-app-logs
  services_s3_bucket_region: us-east-2
  # services_s3_bucket_prefix: cluster_logs

# Secrets
secrets_bucket: "legion-cluster"
secrets_file: "/tmp/{{ cluster_name }}-secrets"

# Dex
dex:
  enabled: true

model_docker_url: nexus-local.cc.epm.kharlamov.biz:8084