# Common
vendor: legion
env_type: ci
env_name: legion-ci
base_domain: legion-ci.epm.kharlamov.biz
route53_zone: epm.kharlamov.biz
# AWS 
aws_region: us-east-2
node_autoscaler_min: 3
node_autoscaler_max: 5
bastion_shape: t2.micro
master_shape: t2.large
node_shape: t2.large
vpc_id: vpc-5729c13e
airflow_rds_shape: "db.t2.medium"
airflow_rds_size: "50"
# Kops
cluster_name: legion-ci.epm.kharlamov.biz
state_store: s3://legion-cluster
aws_image: kope.io/k8s-1.8-debian-jessie-amd64-hvm-ebs-2018-02-08
kubernetes_version: 1.8.7
private_network: '172.31'
cluster_zones:
  - zone_name: us-east-2a
    kops_cidr: "{{ private_network }}.106.0/24"
    kops_utility_cidr: "{{ private_network }}.107.0/24"
  - zone_name: us-east-2b
    kops_cidr: "{{ private_network }}.108.0/24"
    kops_utility_cidr: "{{ private_network }}.109.0/24"
  - zone_name: us-east-2c
    kops_cidr: "{{ private_network }}.110.0/24"
    kops_utility_cidr: "{{ private_network }}.111.0/24"
# Legion specific variables
ssh_public_key: ~/.ssh/id_rsa.pub
certificate_email: legion@epam.com
git_key: "/home/jenkins/deploy.cert"
cert_dir: "/etc/dynssl"
use_https: "yes"
use_https_for_tests: "yes"
nexus_pypi_repo: "https://nexus-local.cc.epm.kharlamov.biz/repository/pypi-hosted/simple"
nexus_docker_repo: "nexus-local.cc.epm.kharlamov.biz:443"
namespace: default
deployment: legion
service_account:
  login:  admin
  password: admin
examples_to_test:
  - Test-Summation
  - Sklearn-Income
  - Digit-Recognition
enclaves:
  - company-a
  - company-b
storageclass: efs
airflow_s3_log_url: 's3://epm-legion-data-ci/airflow-logs/'
airflow_s3_url: 's3://epm-legion-data-ci/'
airflow_expected_output: 'expected-data/'
airflow_pvc: 200m
