# DNS
base_domain: ~       # DNS name of environment
route53_zone: ~      # AWS Route53 zone on which domain will be created (zone should be parked before deploy)


# Common
vendor: ~            # name of vendor, will be used in resource tags
env_name: ~    # short name of env, will be added in resource tags


# Logging
log_level: ~  # log level: debug / info / warning / error


# Ansible variables
tmp_dir: ~                          # directory for storing temporary files (on host during deploy)
cluster_ssh_public_key_path: ~       # public key which will be copied to cluster
persistent_jenkins_volume: ~    # true/false to keep jenkins volume or not on terminate cluster phase


# AWS configuration
aws_region: ~      # target AWS region for EC2 instances
bastion_shape: ~    # shape for bastion nodes (not as part of Kubernetes cluster)
master_shape: ~     # shape for masters
node_shape: ~       # shape for modes
node_autoscaler_min: ~     # minimum count of nodes for autoscaler group
node_autoscaler_max: ~     # maximum count of nodes for autoscaler group
node_extra_shapes: ~        # list of shapes that can be started up during model building of Jenkins (will be shutted down automatically)

node_extra_min: ~          # minimum count of nodes for model building
node_extra_max: ~          # maximum count of nodes for model building

vpc_id: ~               # VPC id where the cluster will be created


# Common cluster configuration for KOPS
cluster_name: ~ # unique KOPS cluster name
state_store: ~  # AWS S3 bucket for storing KOPS state

private_network: ~         # private network prefix
cluster_zones:                    # configuration of cluster zones
  - zone_name: ~
    kops_cidr: ~
    kops_utility_cidr: ~
k8s_master_zones: ~      #list of zones where to create k8s master
default_cluster_roles: ~ #List of IAM roles generated by kops

# TLS sertificates issuing configuration (via Let's Encrypt)
certificate_email: ~      # Let's Encrypt notification email
cert_dir: ~                 # folder for storing SSL certificates on host

# Deploying and test configuration
use_https: ~ # [?]
use_https_for_tests: ~ # [?]
pypi_repo: ~ # repository for Python packages
docker_repo: ~ # docker registry with builded images
namespace: ~      # namespace of core deployment
deployment: ~      # name of deployment
examples_to_test: ~      # which Jenkins examples will be executed in tests

model_id_to_test: ~  # id of model which will be tested in EDI tests
enclaves: ~ # list of enclaves which will be automatically deployed after Legion deploy

legion_data_bucket_prefix: ~ # S3 bucket name prefix
legion_data_s3_bucket: ~ # s3 bucket for enclave data

# Kube fluentd properties
# Cluster logs
kube_fluentd:
  kube_s3_bucket_name: ~
  kube_s3_bucket_region: ~
  # kube_s3_bucket_prefix: ~
  system_s3_bucket_name: ~
  system_s3_bucket_region: ~
  # system_s3_bucket_prefix: ~
  services_s3_bucket_name: ~
  services_s3_bucket_region: ~
  # services_s3_bucket_prefix: ~

# Addons configuration
storageclass: ~              # Which storage use in PVCs
dashboard:                     # Kubernetes dashboard configuration
  version: ~             # Dashboard version
  insecure: ~               # Allow insecure access

secrets_bucket: ~               # S3 bucket with secrets
secrets_file: ~  # path for temporary storage

collector:    # event collector configuration
  replicas: ~
  region: ~ # bucket region

# hide_edge_page: ~ # (Optional) 'false' - Edge home page os visible (default value)
max_token_ttl_minutes: ~  # Max TTL for JWT generated for a model

# k8s_api_retry_number_max_limit: count of retries for confirming of k8s operations
# k8s_api_retry_delay_sec: wait between confirming of k8s operations

model_docker_url: ~