# AWS resources configuration
aws:
  account_id: ~
  rds: # credentials for dynamically deployed RDS
    username: ~
    password: ~
    database_name: ~

# Airflow configuration
airflow:
  connections:  # list of airflow connections that will be automatically added during deploy
  # Connection to Aurora


  # Connection to S3
  - connection_id: ~
    connection_type: ~


  # SMTP credentials for email notifications
  email:
    smtp_host: ~
    smtp_starttls: ~
    smtp_ssl: ~
    smtp_user: ~
    smtp_port: ~
    smtp_password: ~
    smtp_mail_from: ~

  # Fernet key
  fernet_key: ~

  # Airflow-slack integration
  slack:
    channel: ~
    username: ~
    token: ~
  webserver:
    email_backend: ~ # set email_backend to empty for Slack disabling notifications

# Fluentd configuration for event log collection
fluentd:
  aws: # Credentials for storing data on S3
    secret_access_key: ~
    access_key_id: ~

external_access_sgs: ~ # list of AWS SG that should be added on ELB

allowed_wan_ips: ~ # list of whitelisted CIDRs

jenkins_cc_sg: ~ # CC Jenkins Security Group to be whitelisted on cluster


# Airflow auth configuration
airflow_auth:
  enabled: ~
  auth_backend: ~  # Python auth backend

# DEX configuration
dex:
  enabled: ~
  config:
    client_id: ~ # env. name ()
    client_secret: ~ # randomly generated 24-len password
    # connectors:
    # - type: ~
    #   id: ~
    #   name: ~
    #   config:
    #     clientID: ~
    #     clientSecret: ~
    #     redirectURI: ~ # DEX callback URL
    staticPasswords:  # static hardcoded passwords for test
    - email: ~
      password: ~
      hash: ~ # bcrypt hash of the string "password"
      username: ~
      userID: ~
  groups_binding: #group mappings
    kubernetes: ~
    jenkins: ~
    airflow: ~
    edge: ~
    edi: ~

# API Security configuration
api:
  jwt_secret: ~ # JWT secret
  jwt_ttl_minutes: ~ # JWT TTL in minutes (e.g. 120)
  #jwt_exp_datetime: "2018-12-31T23:59:59" # (optional) JWT expiration datetime in "%Y-%m-%dT%H:%M:%S" format