{{- define "dex-config" }}
issuer: https://dex.beta.iqvia.kharlamov.biz
storage:
  type: kubernetes
  config:
    inCluster: true

web:
{{- if .Values.ingress.enabled }}
  http: 0.0.0.0:{{ .Values.service.targetPort }}
{{- else }}
  https: 0.0.0.0:{{ .Values.service.targetPort }}
  tlsCert: /tls/tls.crt
  tlsKey: /tls/tls.key
{{- end }}

connectors:
{{ toYaml .Values.connectors | indent 2 }}

oauth2:
  skipApprovalScreen: {{ .Values.skipApprovalScreen }}

staticClients:
{{ toYaml .Values.staticClients | indent 2 }}

logger:
{{ toYaml .Values.logger | indent 2 }}


enablePasswordDB: {{ .Values.enablePasswordDB }}

staticPasswords:
{{ toYaml .Values.staticPasswords | indent 2 }}

{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
    app: {{ template "dex.name" . }}
    chart: {{ template "dex.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  config.yaml: |-
    {{ include "dex-config" . | b64enc }}
